import { useEffect, useState } from 'react'

const API = import.meta.env.VITE_API_BASE || '/api'
const DEMO = import.meta.env.VITE_DEMO_BASE || '/demo'
const DEMO_MODE = import.meta.env.VITE_DEMO_MODE !== 'false'
const money = (v) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(v || 0))
const formatDate = (v) => v ? new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${String(v).slice(0, 10)}T00:00:00`)) : 'Not stated'
const formatDateTime = (v) => v ? new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(v)) : ''
const go = (path) => { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }
const stageTone = (stage) => ({ none: 'neutral', nudge: 'blue', firm: 'amber', formal: 'red' }[stage] || 'neutral')
const statusTone = (status) => status === 'paid' ? 'green' : status === 'partially_paid' ? 'blue' : status === 'escalation_exhausted' ? 'red' : 'neutral'

function Badge({ children, tone = 'neutral' }) { return <span className={`badge badge-${tone}`}>{String(children || '').replaceAll('_', ' ')}</span> }
function Metric({ label, value, note, tone }) { return <section className={`metric ${tone ? `metric-${tone}` : ''}`}><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</section> }
function PageTitle({ eyebrow, title, children }) { return <div className="page-title"><div><p>{eyebrow}</p><h1>{title}</h1></div>{children}</div> }

function InvoiceTable({ invoices }) {
  if (!invoices.length) return <div className="empty-state">No invoices found in the current workspace.</div>
  return <div className="table-wrap"><table><thead><tr><th>Customer / invoice</th><th>Collection state</th><th>Due</th><th>Reliability</th><th className="amount-cell">Outstanding</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id} onClick={() => go(`/invoice/${invoice.id}`)}><td><button className="invoice-link" onClick={(e) => { e.stopPropagation(); go(`/invoice/${invoice.id}`) }}><span>{invoice.customer_name}</span><small>INV-{String(invoice.id).padStart(5, '0')}</small></button></td><td><div className="badge-row"><Badge tone={statusTone(invoice.status)}>{invoice.status}</Badge><Badge tone={stageTone(invoice.current_stage)}>{invoice.current_stage}</Badge></div>{invoice.needs_review && <small className="review-note">Human review required</small>}</td><td><strong>{invoice.days_overdue} days</strong><small>Due {formatDate(invoice.due_date)}</small></td><td><div className="score"><i style={{ width: `${Math.round(Number(invoice.reliability_score || 0) * 100)}%` }} /><span>{Number(invoice.reliability_score || 0).toFixed(2)}</span></div></td><td className="amount-cell"><strong>{money(Number(invoice.amount) - Number(invoice.amount_paid || 0))}</strong><small>of {money(invoice.amount)}</small></td></tr>)}</tbody></table></div>
}

function DemoBar({ refresh }) {
  const [clock, setClock] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('')
  useEffect(() => { fetch(`${DEMO}/clock`).then((r) => r.json()).then((d) => setClock(d.now)).catch(() => {}) }, [])
  if (!DEMO_MODE) return null
  const action = async (path, body) => { setBusy(true); setNotice(''); try { const r = await fetch(`${DEMO}/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body || {}) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.detail || 'Demo action failed'); setClock(d.now || ''); setNotice(d.message || 'Demo state updated.'); window.dispatchEvent(new Event('demo-clock-changed')); await refresh() } catch (error) { setNotice(error.message) } finally { setBusy(false) } }
  return <section className="demo-bar"><div className="demo-copy"><Badge tone="purple">Demo mode</Badge><span>{clock ? `Virtual date · ${formatDateTime(clock)}` : 'Loading virtual clock…'}</span></div><div className="demo-actions"><button disabled={busy} onClick={() => action('advance-clock', { days: 1 })}>+1 day</button><button disabled={busy} className="button-dark" onClick={() => action('advance-clock', { days: 7 })}>+7 days</button><button disabled={busy} className="button-quiet" onClick={() => action('reset')}>Reset</button></div>{notice && <small>{notice}</small>}</section>
}

function Dashboard({ invoices, metrics }) {
  const open = invoices.filter((i) => ['unpaid', 'partially_paid'].includes(i.status)); const urgent = invoices.filter((i) => i.current_stage === 'formal' || i.needs_review).length
  return <><PageTitle eyebrow="Collections workspace" title="Recovery at a glance"><button className="button-primary" onClick={() => go('/simulate')}>Record customer reply</button></PageTitle><div className="metric-grid"><Metric label="Open receivables" value={money(metrics.total_unpaid_inr)} note="Across active invoices" /><Metric label="Active recovery" value={metrics.active_unpaid_invoices || open.length} note="Invoices being monitored" tone="blue" /><Metric label="Needs attention" value={metrics.human_review_required || urgent} note="Human decision required" tone="amber" /></div><section className="panel watchlist"><div className="panel-head"><div><h2>Recovery watchlist</h2><p>Every collection action is logged to its invoice record.</p></div><span className="muted">{invoices.length} invoices</span></div><InvoiceTable invoices={invoices} /></section></>
}

function InvoiceDetail({ id, refresh }) {
  const [invoice, setInvoice] = useState(null); const [audit, setAudit] = useState(null); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  const load = async () => { const [a, b] = await Promise.all([fetch(`${API}/invoices/${id}`), fetch(`${API}/invoices/${id}/ledger`)]); if (!a.ok || !b.ok) throw new Error('Could not load invoice details.'); setInvoice(await a.json()); setAudit(await b.json()) }
  useEffect(() => { load().catch((e) => setNotice(e.message)) }, [id]); useEffect(() => { window.addEventListener('demo-clock-changed', load); return () => window.removeEventListener('demo-clock-changed', load) }, [id])
  const request = async (path) => { setBusy(true); try { const r = await fetch(`${API}/invoices/${id}/${path}`, { method: 'POST' }); const d = await r.json(); if (!r.ok) throw new Error(d.detail || 'Action failed'); setNotice(path === 'verify' ? (d.chain_integrity_valid ? 'Integrity verified. Every ledger hash and link is intact.' : 'Integrity check failed.') : d.message || 'Action completed.'); await load(); await refresh() } catch (e) { setNotice(e.message) } finally { setBusy(false) } }
  if (!invoice) return <div className="loading">Loading invoice record…</div>
  const outstanding = Number(invoice.amount) - Number(invoice.amount_paid || 0)
  return <><button className="back-link" onClick={() => go('/dashboard')}>← Back to collections</button><PageTitle eyebrow={`Invoice INV-${String(invoice.id).padStart(5, '0')}`} title={invoice.customer_name}><div className="badge-row"><Badge tone={statusTone(invoice.status)}>{invoice.status}</Badge><Badge tone={stageTone(invoice.current_stage)}>{invoice.current_stage}</Badge></div></PageTitle><div className="invoice-summary"><div><span>Outstanding</span><strong>{money(outstanding)}</strong><small>of {money(invoice.amount)} total</small></div><div><span>Due date</span><strong>{formatDate(invoice.due_date)}</strong><small>{invoice.days_overdue} days overdue</small></div><div><span>Reliability score</span><strong>{Number(invoice.reliability_score).toFixed(2)}</strong><small>{invoice.next_action}</small></div><div className="summary-actions"><button disabled={busy} className="button-primary" onClick={() => request('razorpay')}>Create payment link</button><button disabled={busy} onClick={() => request('sync-payment')}>Sync payment</button><button disabled={busy} className="button-quiet" onClick={() => request('verify')}>Verify ledger</button></div></div>{notice && <div className="notice">{notice}</div>}<div className="detail-grid"><section className="panel"><div className="panel-head"><div><h2>Commitments</h2><p>What the customer has explicitly committed to.</p></div></div>{invoice.promises?.length ? <div className="commitments">{invoice.promises.map((p) => <article key={p.id}><Badge tone={p.status === 'broken' ? 'red' : p.status.startsWith('kept') ? 'green' : 'blue'}>{p.status}</Badge><strong>{p.amount ? money(p.amount) : 'Amount not stated'}</strong><span>{formatDate(p.promised_date)}</span><p>{p.source_text}</p></article>)}</div> : <div className="empty-state">No payment commitment has been recorded.</div>}</section><section className="panel provider"><div className="panel-head"><div><h2>Payment rail</h2><p>Razorpay test-mode identifiers.</p></div></div><dl><dt>Invoice</dt><dd>{invoice.razorpay_invoice_id || 'Not created'}</dd><dt>Payment link</dt><dd>{invoice.razorpay_payment_link_id || 'Not created'}</dd></dl></section></div><section className="panel timeline-panel"><div className="panel-head"><div><h2>Audit timeline</h2><p>Append-only event history for this invoice.</p></div><Badge tone={audit?.chain_integrity_valid ? 'green' : 'red'}>{audit?.chain_integrity_valid ? 'Verified' : 'Unverified'}</Badge></div><div className="timeline">{audit?.ledger?.map((event) => <article key={event.id}><i /><div><span>{formatDateTime(event.timestamp)}</span><strong>{event.event.replaceAll('_', ' ')}</strong><pre>{JSON.stringify(event.payload, null, 2)}</pre></div></article>)}</div></section></>
}

function Simulate({ invoices, refresh }) {
  const [id, setId] = useState(''); const [text, setText] = useState('We can release 50% next Wednesday and the balance after our customer settles.'); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false)
  useEffect(() => { if (!id && invoices[0]) setId(String(invoices[0].id)) }, [invoices, id])
  const submit = async () => { setBusy(true); try { const r = await fetch(`${API}/simulate/reply`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ invoice_id: Number(id), text }) }); const data = await r.json(); setResult(data); if (r.ok) await refresh() } finally { setBusy(false) } }
  return <><PageTitle eyebrow="Customer communication" title="Record a payment commitment" /><div className="simulate-grid"><section className="panel form-panel"><label>Invoice<select value={id} onChange={(e) => setId(e.target.value)}>{invoices.map((i) => <option key={i.id} value={i.id}>INV-{String(i.id).padStart(5, '0')} · {i.customer_name}</option>)}</select></label><label>Customer reply<textarea rows="9" value={text} onChange={(e) => setText(e.target.value)} /></label><button disabled={!id || busy} className="button-primary full-button" onClick={submit}>{busy ? 'Extracting…' : 'Extract commitment'}</button><p className="form-note">CHASR logs the source text and only persists structured commitments the model identifies.</p></section><section className="panel result-panel"><div className="panel-head"><div><h2>Structured result</h2><p>Validated before it affects the collection policy.</p></div></div>{result ? <>{result.extraction?.commitments?.length ? result.extraction.commitments.map((c, index) => <div className="result-row" key={index}><span>Commitment {index + 1}</span><strong>{c.amount ? money(c.amount) : 'Amount not stated'}</strong><p>{formatDate(c.promised_date)} · {c.confidence || 'vague'}</p></div>) : <div className="empty-state">No clear commitment found. The reply is still recorded in the audit log.</div>}<div className={`policy-result ${result.needs_review ? 'policy-review' : ''}`}><span>CHASR decision</span><strong>{result.needs_review ? 'Human review required' : 'Scheduler will apply the collection policy'}</strong></div></> : <div className="empty-state">Submit a reply to view the extracted commitment and next step.</div>}</section></div></>
}

function Results() {
  const [data, setData] = useState(null); useEffect(() => { fetch(`${API}/results`).then((r) => r.json()).then(setData) }, []); if (!data) return <div className="loading">Loading evaluation…</div>
  return <><PageTitle eyebrow="Evaluation" title="Held-out recovery performance" /><p className="page-intro">{data.methodology}</p><div className="metric-grid results-metrics"><Metric label="Batch size" value={data.batch_size} /><Metric label="Observed recovered" value={money(data.observed_recovered_inr)} tone="green" /><Metric label="Precision" value={data.precision} tone="blue" /><Metric label="Recall" value={data.recall} tone="blue" /></div><div className="detail-grid"><section className="panel"><div className="panel-head"><div><h2>Adaptive targets</h2><p>Reliability-informed collection set.</p></div></div><div className="id-list">{data.adaptive_target_invoice_ids?.map((i) => <span key={i}>INV-{i}</span>) || 'None'}</div></section><section className="panel"><div className="panel-head"><div><h2>Fixed schedule</h2><p>Same batch under a non-adaptive baseline.</p></div></div><div className="id-list">{data.baseline_target_invoice_ids?.map((i) => <span key={i}>INV-{i}</span>) || 'None'}</div></section></div><section className="panel exceptions"><div className="panel-head"><div><h2>Exceptions requiring judgement</h2><p>Cases deliberately not treated as automatic recovery wins.</p></div></div>{data.exceptions?.length ? data.exceptions.map((e) => <div className="exception" key={e.invoice_id}><strong>INV-{e.invoice_id} · {e.customer}</strong><span>{money(e.amount)}</span><p>{e.reason}</p></div>) : <div className="empty-state">No exceptions in this held-out batch.</div>}</section></>
}

export default function App() {
  const [path, setPath] = useState(window.location.pathname === '/' ? '/dashboard' : window.location.pathname); const [invoices, setInvoices] = useState([]); const [metrics, setMetrics] = useState({})
  const refresh = async () => { const [i, m] = await Promise.all([fetch(`${API}/invoices`).then((r) => r.json()), fetch(`${API}/dashboard`).then((r) => r.json())]); setInvoices(i); setMetrics(m) }
  useEffect(() => { refresh(); const handler = () => setPath(window.location.pathname); window.addEventListener('popstate', handler); return () => window.removeEventListener('popstate', handler) }, [])
  const is = (target) => path === target || (target === '/dashboard' && path.startsWith('/invoice/'))
  const content = path.startsWith('/invoice/') ? <InvoiceDetail id={path.split('/').pop()} refresh={refresh} /> : path === '/simulate' ? <Simulate invoices={invoices} refresh={refresh} /> : path === '/results' ? <Results /> : <Dashboard invoices={invoices} metrics={metrics} />
  return <div className="app"><aside><button className="brand" onClick={() => go('/dashboard')}><b>CH</b><span>CHASR<small>RECOVERY OPS</small></span></button><nav><button className={is('/dashboard') ? 'active' : ''} onClick={() => go('/dashboard')}><i>▦</i>Collections</button><button className={is('/simulate') ? 'active' : ''} onClick={() => go('/simulate')}><i>↗</i>Customer reply</button><button className={is('/results') ? 'active' : ''} onClick={() => go('/results')}><i>◌</i>Performance</button></nav><div className="side-note"><span>COLLECTIONS POLICY</span><p>Deterministic escalation. Every action audited.</p></div></aside><main><header className="topbar"><span>Revenue recovery</span><div><i className="live-dot" />System operational</div></header><div className="content"><DemoBar refresh={refresh} />{content}</div></main></div>
}
